### PR TITLE
writer: add ntsc timebase converter to work with AE-style timebases

### LINKED ISSUE #12: AE exporter 29.97 timebase differ from QT variant
Timebase of 29.97 files from AE exporter plugin is 32768/982057,
and it differ from QT variant with expected 1001/30000

Diagnostic can be done with ffprobe:
`ffprobe -v error -show_format -show_streams 1.mov AE-PL-2997`
 `ffprobe -v error -show_entries stream=index,codec_time_base AE-PL-2997.mov`
Here is result of ffprobes: http://mergely.com/ccCLMh8A/

Issue not happens during AE-thru-AME export and not happens during normal QT exports.

So it seems Premiere and AfterEffects SDKs provide different timebase num/den values.
Looks like AE provide 1000/29970 (not 1001/30000) and then ffmpeg mess it even more...

Doesn`t find algorithm solution so far, only switch table with all timebase variants...

https://ae-plugin-sdk-guide.readthedocs.io/ppro/basic-host-differences.html#time-values

### PR DESCRIPTION
**Pull request by exscriber**
Fixes #12 
1) Refactor std:gcd() to av_reduce() - ffmpeg`s gcd with usefull aditions.
2) Table based NTSC timebases converter from AE-style to Premiere style (n/1001).
It doesn`t do anything with other timebases.

Thanks @bangnoise for research direction.

### CODE REVIEW

**Comment by GregBakker** [comment]
Just added a request for some clarifications to #15, wish to make sure I understand under which circumstances allowing AEX's timebase to propagate causes problems.

Only issue I have really is that altering the fraction from AEX changes the idea of which frame should be displaying at a given clock time (even fractionally) - although if AEX itself does different things if you export via Premiere, maybe that's not such an issue o_O - [although that might be caused by us looking up a framerate in the Premiere plugin]

**Comment by exscriber** [comment]
I'm not sure what exactly AE to Premiere conversion does. (does it multiply timebase by some constant or just replace it as in this PR)
Code in convertNTSCTimebase() is what ffmpeg's other formats does, for example [mxf muxer](https://github.com/FFmpeg/FFmpeg/blob/a174e5f8da77d17dc16227f94eb14db7fd0365a4/libavformat/mxf.c#L144-L174).

If it can cause problems, i can hide conversion in #ifdef macro.
Any suggestions for test cases? I test conversion code internally, and for my cases it work ok.

Premiere plugin doesn't lock framerate to GUI table, i can render AE Comp with any fps thru AME.
And during test's i catch problem with std::gcd() that fixed by av_reduce():
AE 29.0fps rendered thru AME - very strange as 29fps is not fractional, but Premiere think it is...
av_reduce() have special branch to work with things like this one.

**Comment by GregBakker** [comment]
As per our discussion, I'm implementing this in the Adobe output_module as that's where the correct timebase num / den needs to be guessed. In AfterEffects if the supplied fps is close to an official fps, we will lock to it.

AfterEffects supported framerates (on compositions) are 8 12 15 23.976 24 25 29.97 30 48 50 60 120,
the fractional ones typically have a denominator of 1001. Any supplied fps fractionally within 0.0001 of one of these will be locked to it, otherwise will pass through.

Would prefer to make MovieWriter do *exactly* what it's told with respect to timebase num den, and make it the clients' responsibility to compute the correct value. So no magic under the hood.

**Comment by GregBakker** [comment]
...but having said this, maybe a utility function alongside it is the best idea.

**Comment by GregBakker** [comment]
I've now integrated a utility function alongside MovieWriter that's implementing similar functionality, SimplifyAndSnapToMpegFrameRate. This is used by both the AfterEffects and Premiere plugins.

**Pull request closed without merging**
